### ISSUE TITLE
The switch from synchronous I2C writes to queued asynchronous I2C writes

### ISSUE THREAD

**Issue by fivdi** [nebrius/raspi-io-core#12]
In the past, raspi-io used synchronous methods for I2C writes. For example, `writeSync` [here](https://github.com/nebrius/raspi-io/blob/7.0.0/index.js#L564) and `writeByteSync` [here](https://github.com/nebrius/raspi-io/blob/7.0.0/index.js#L573). Today, I2C write are queued and written using asynchronous methods. For example, `write` [here](https://github.com/nebrius/j5-io/blob/3.1.0/src/managers/i2c.ts#L97) and `writeByte` [here](https://github.com/nebrius/j5-io/blob/3.1.0/src/managers/i2c.ts#L103).

On the other hand, Johnny-Five has I2C code that implicitly assumes that I2C writes are synchronous. As an example, to initialize an I2C LCD display, Johnny-Five runs [this blocking synchronous code](https://github.com/rwaldron/johnny-five/blob/v1.3.1/lib/lcd.js#L416-L451). The calls to sleep in this blocking code are important and essential. In the past, when raspi-io used synchronous methods for I2C writes this code was highly likely to have functioned correctly. Today, raspi-io queues I2C commands and uses asynchronous methods for I2C writes and the code is far less likely to function correctly. Today, sleeps can complete before the asynchronous writes that they are waiting for to complete have actually completed.

I think today’s queued asynchronous I2C writes in raspi-io are the cause of [this](https://github.com/rwaldron/johnny-five/issues/1639) Johnny-Five issue.

**Comment by nebrius** [comment]
Hrmmm...that’s unfortunate. Switching to this async format was one of the big ways I fixed high CPU usage, so I _really_ don’t want to revert it. I’m traveling right now, but I’ll think on this.

My current thought is to add an `i2cSleep` method to the IO plugin protocol and use that if available, otherwise use standard sleep. In J5-IO, this would be another queued operation.

As a side note, firmata is _all_ implicit async code like this since it has to communicate over the wire. I’d _guess_ the processing power of a computer vs RPi masks the fact that this is happening due to lower latency and better predictability (context switches are way faster, etc)

**Comment by fivdi** [comment]
> Switching to this async format was one of the big ways I fixed high CPU usage, so I really don’t want to revert it.

I can understand not wanting to revert it and it's entirely up to you how to proceed. That being said, I don't see how changing to async alone can decrease CPU usage. If anything, it should increase it slightly as it results in more context switching. CPU usage can be quite high with the current version of raspi-io. For example, the last time I checked, running [this bme280 program](eg/multi-BME280.js) results in about 60% CPU usage on a Pi 3.

> My current thought is to add an i2cSleep method to the IO plugin protocol and use that if available

Implementing such a change would require a considerable amount of time.

**Comment by nebrius** [comment]
> That being said, I don't see how changing to async alone can decrease CPU usage. If anything, it should increase it slightly as it results in more context switching. CPU usage can be quite high with the current version of raspi-io. For example, the last time I checked, running this bme280 program results in about 60% CPU usage on a Pi 3.

60% is a major improvement over the 80-100% Raspi IO had _at idle_ in version 9 😉

Using synchronous calls for I/O in Node.js is antithetical to how Node.js itself works, because we're intentionally blocking the event loop. TBH if the performance cost of context switches is the bottleneck in someone's app, then they shouldn't be using Node.js at all and should be using C++ instead, and Raspi IO is the wrong library for them. That's not my use case and I don't intend to optimize for it.

> Implementing such a change would require a considerable amount of time.

Doesn't seem like it to me. We look for the instances of `sleep(n)` used for I2C code (perhaps on a case by case basis starting with LCD) and replace it with:

```JavaScript
if (io.plugin.i2cSleep) {
  io.plugin.i2cSleep(n);
} else {
  sleep(n);
}
```

It's really just a search and replace, and I'd rather spend my time doing that than reverting this code.

As another side note: the amount of blocking code in Johnny-Five is itself a problem, and as long as that code is around, Johnny-Five will never be a best-in-class Node.js library. To be super frank: the download numbers for Johnny-Five have been dropping steadily for some time, and if we don't modernize the framework to make it relevant again, then all this discussion is moot anyways IMO.

**Comment by fivdi** [comment]
> 60% is a major improvement over the 80-100% Raspi IO had at idle in version 9 :wink: 

True :smile: 


>My current thought is to add an i2cSleep method to the IO plugin protocol and use that if available
> 
> > Implementing such a change would require a considerable amount of time.
> 
> Doesn't seem like it to me. We look for the instances of `sleep(n)` used for I2C code (perhaps on a case by case basis starting with LCD) and replace it with:
> 
> ```js
> if (io.plugin.i2cSleep) {
>   io.plugin.i2cSleep(n);
> } else {
>   sleep(n);
> }
> ```
> 
> 
> It's really just a search and replace, and I'd rather spend my time doing that than reverting this code.

I think there's going to be more to it than changing the calls to sleep. Changing the calls to sleep should be fairly easy as there's not many of them. It's also code like [this](https://github.com/rwaldron/johnny-five/blob/v1.3.1/lib/imu.js#L586-L592) where it's a little more subtle:
```js
            io.i2cWriteReg(address, this.REGISTER.AXIS_MAP_SIGN_ADDR, axisSign);

            // Set operational mode to "nine degrees of freedom"
            setTimeout(function() {
              io.i2cWriteReg(address, this.REGISTER.OPR_MODE_ADDR, this.REGISTER.OPR_MODES.NDOF);
              resolve();
            }.bind(this), 10);
```

**Comment by nebrius** [comment]
> I think there's going to be more to it than changing the calls to sleep. Changing the calls to sleep should be fairly easy as there's not many of them. It's also code like this where it's a little more subtle:

That's true, those will indeed be harder to spot. I'm OK with that though...magic numbers, such as pre-defined sleep/setTimeout/etc. lengths, will always be inherently buggy. I think it's fine to fix them as they're discovered.

**Comment by nebrius** [comment]
OH OH OH! I know _exactly_ what is going on, and why the LCD now breaks. We don't need to do an `i2cSleep` thing...it's not the queueing mechanism at all causing the issue. It's the `sleep` method.

So here's what's happening:

1. Johnny-Five calls two I2C methods at https://github.com/rwaldron/johnny-five/blob/v1.3.1/lib/lcd.js#L420-L421
2. This call winds through J5 to J5-IO and enqueues _two_ I2C operations at https://github.com/nebrius/j5-io/blob/master/src/managers/i2c.ts#L208
3. Best case scenario, there are no other I2C operations queued up, so the _first_ item gets dequeued and we call into Raspi.js at https://github.com/nebrius/j5-io/blob/master/src/managers/i2c.ts#L94-L107, which directly calls i2c-bus. This is asynchronous, so the call is dispatched into the event loop for it to do its thing in C++ land. One I2C write is (most likely) issued on the wire here, but I'm not sure and it could be zero writes, but it doesn't matter because of what comes next
4. The stack unwinds back to https://github.com/rwaldron/johnny-five/blob/v1.3.1/lib/lcd.js#L422
5. Sleep is called at https://github.com/rwaldron/johnny-five/blob/v1.3.1/lib/lcd.js#L422. Sleep doesn't actually _sleep_. Rather, it's a while loop so it pegs the CPU core at 100% and (this is the important part) blocks the event loop so we never get the I2C write completion callback for the first operation.
6. The while loop exits
7. The I2C write callback is called because the event loop is now unblocked, which goes through the J5-IO queueing mechanism and causes the second write to now be issued (which is supposed to happen _before_ sleep is called, not after).

Anyways, tl;dr, Johnny-Five is blocking the event loop and causing the writes to be issued out of order w.r.t. sleep calls.

As such, this is a bug in Johnny-Five, and needs to be fixed there (probably with an async function).
